openapi: 3.0.0
info:
  title: "Beep Beep Statistics Webservice"
  description: "This is a statistics web server for the Beep Beep application for retrieving statistics about your runs in a visual graphical format. For more information, visit the Github repository: https://github.com/MFranceschi6/BeepBeep-statistics"
  license:
    name: APLv2
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "0.1.0"
  termsOfService: "https://github.com/MFranceschi6/BeepBeep-statistics"

servers:
  - url: 0.0.0.0:5001
components:
  schemas:
  
    NumericalArray:
      type: array
      items:
        type: integer
      minItems: 0
      
      
    DistanceArray:
      type: array
      $ref: '#/components/schemas/NumericalArray'
    
    AverageSpeedArray:
      type: array
      $ref: '#/components/schemas/NumericalArray'
    
    AverageHeartRateArray:
      type: array
      $ref: '#/components/schemas/NumericalArray'
      
    ElevationGainArray:
      type: array
      $ref: '#/components/schemas/NumericalArray'
      
    ElapsedTimeArray:
      type: array
      $ref: '#/components/schemas/NumericalArray'

    AllNumericalArrays:
      allOf:
      - type: object
        properties:
          distance_array:
            type: object
            $ref: '#/components/schemas/DistanceArray'
          average_speed_array:
            type: object
            $ref: '#/components/schemas/AverageSpeedArray'
          average_heart_rate_array:
            type: object
            $ref: '#/components/schemas/AverageHeartRateArray'
          elevation_gain_array:
            type: object
            $ref: '#/components/schemas/ElevationGainArray'
          elapsed_time_array:
            type: object
            $ref: '#/components/schemas/ElapsedTimeArray'
            
      
    OneNumericalArray:
      oneOf:
      - type: object
        properties:
          distance_array:
            type: object
            $ref: '#/components/schemas/DistanceArray'
          average_speed_array:
            type: object
            $ref: '#/components/schemas/AverageSpeedArray'
          average_heart_rate_array:
            type: object
            $ref: '#/components/schemas/AverageHeartRateArray'
          elevation_gain_array:
            type: object
            $ref: '#/components/schemas/ElevationGainArray'
          elapsed_time_array:
            type: object
            $ref: '#/components/schemas/ElapsedTimeArray'
    
      
paths:
  /statistics/{user_id}/:
    parameters:
      - in: path
        name: user_id
        description: "The id of the user whose statistics you want to access"
        required: true
        schema:
          type: integer
    get:
      operationId: "getAllStatisticsbyUserID"
      description: "By accessing this page and providing an existing user ID, you retrieve a set of 5 arrays about the temporal statistics of your runs for the following attributes, respectively: 'distance', 'average speed', 'average heartrate'. 'total elevation gain', 'elapsed time'."
      responses:
        '200':
          description: "All runs' statistics for the user whose ID was provided"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllNumericalArrays'
        '400':
          description: "Invalid user ID supplied"
        '404':
          description: "User not found for the user ID supplied. "
      security:
      - api_key: []
      
  /statistics/{user_id}/{statistics_id}:
    parameters:
      - in: path
        name: user_id
        description: "The id of the user whose statistics you want to access"
        required: true
        schema:
          type: integer
      - in: path
        name: statistics_id
        description: "Based on the statistics ID passed, one of the following arrays is returned: 1 = distance array; 2 = average speed array; 3 = average heartrate array ; 4 = total elevation gain array; 5 = elapsed time array."
        required: true
        schema:
          type: integer
    get:
      operationId: "getSingleStatisticsbyUserID"
      description: "By accessing this page and providing an existing user ID, you retrieve a set of 5 arrays about the temporal statistics of your runs for the following attributes, respectively: 'distance', 'average speed', 'average heartrate'. 'total elevation gain', 'elapsed time'."
      responses:
        '200':
          description: "Runs' statistics of one single statistics type for the user whose ID was provided"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OneNumericalArray'
        '400':
          description: "Invalid user ID supplied or invalid statistics ID supplied."
        '404':
          description: "User not found for the user ID supplied."
      security:
      - api_key: []